export const API_ENDPOINTS = {
	HOME: "/home",
	LOGIN: "/auth/login",
	REGISTER: "/auth/register",
	PRODUCTS: "/products",
	CATEGORIES: "/categories",
	BRANDS: "/brands",
	CART: "/cart",
	ADD_TO_CART: "/add-to-cart",
	WISHLIST: "/wishlist",
	TOGGLE_WISHLIST: "/wishlist/toggle",
	CHECKOUT_SUMMARY: "/checkout/summary",
	COUNTRIES: "/countries",
	GOVERNORATES: "/governorates",
	CITIES: "/cities",
	SETTINGS: "/settings",
	CONTACT_US: "/contact-us",
	BEST_SELLERS: "/best-sellers",
	BLOGS: "/blogs",
	FLASH_SALES: "/flash-sales",
	LATEST_PRODUCTS: "/latest-products",
	PROFILE: "/profile",
	PAYMENT_METHODS: "/payment-methods",
};

export default API_ENDPOINTS;
